org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=net.liopyu.entityjs
modId=entityjs
modName=EntityJS
modVersion=2.4.6
minecraftVersion=26.1.2
neoforgeVersion=26.1.2.29-beta

modLicense=GNU General Public License Version 3
modAuthors=Liopyu,Too Much Mail
modDescription=Entity Registry Addon Mod For KubeJS
minecraftVersionRange=[26.1.2,26.2)
neoforgeVersionRange=[26.1.2.29-beta,)
loaderVersionRange=[4,)
kubejsVersion=26.1.2-8.0.0-SNAPSHOT

rhinoVersion=2101.2.7-build.81
geckolibVersion=5.5.1
