org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
parchment_version=2023.09.03
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
fabric_loader_version=0.15.11
fabric_api_version=0.92.1+1.20.1
architectury_api_version=9.2.14
architectury_loom_version=1.6-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT
shadow_version=8.1.1

mod_version=0.7.4
mod_id=entityjs
mod_name=EntityJS
mod_license=GNU General Public License Version 3
mod_authors=Liopyu,Too Much Mail
mod_description=Entity Registry Addon Mod For KubeJS
maven_group=net.liopyu.entityjs
archives_base_name=entityjs
enabled_platforms=fabric,forge

kubejs_fabric_version=2001.6.5-build.14
kubejs_forge_version=2001.6.5-build.16
rhino_fabric_version=2001.2.2-build.18
rhino_forge_version=2001.2.3-build.10
geckolib_fabric_version=4.4.4
geckolib_forge_version=1.20.1:4.4.2
probejs_fabric_snippet=585406:5227391
probejs_forge_snippet=585406:5227399
mixin_version=0.8.5