modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "https://github.com/liopyu/EntityJS/issues" #optional
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
[[mods]] #mandatory
modId = "entityjs" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
credits = "Liopyu, Too Much Mail" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[dependencies.entityjs]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.entityjs]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.entityjs]]
modId = "kubejs"
mandatory = true
versionRange = "[2100.7.0-build.83,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entityjs]]
modId = "geckolib"
mandatory = true
versionRange = "[4.5,)"
ordering = "NONE"
side = "BOTH"
