modLoader = "javafml" #mandatory
loaderVersion = "${loaderVersionRange}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${modLicense}"
issueTrackerURL = "https://github.com/liopyu/EntityJS/issues" #optional
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
[[mods]] #mandatory
modId = "entityjs" #mandatory
version = "${version}" #mandatory
displayName = "${modName}" #mandatory
credits = "Liopyu, Too Much Mail" #optional
authors = "${modAuthors}" #optional
description = '''${modDescription}'''
[[dependencies.entityjs]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neoforgeVersionRange}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.entityjs]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.entityjs]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejsVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entityjs]]
modId = "geckolib"
mandatory = true
versionRange = "[${geckolibVersion},)"
ordering = "NONE"
side = "BOTH"
[[mixins]]
config = "entityjs.mixins.json"